## What Is NumPy??

- NumPy stands for Numerical Python. It is a Python library used for fast numerical and mathematical computations. NumPy is mainly used in Data Science, Machine Learning, and scientific computing.

- The core feature of NumPy is the ndarray (N-dimensional array). An ndarray stores data in the form of arrays and allows fast operations on large amounts of data.

- NumPy arrays are faster and more memory efficient than normal Python lists because they store elements of the same data type together.

- With NumPy, we can perform:

-- Mathematical operations
-- Statistical calculations
-- Matrix operations
-- Array manipulation
-- Random number generation
-- Linear algebra operations

- NumPy is widely used because many libraries like Pandas, Scikit-learn, TensorFlow, and PyTorch are built on top of it.

- In simple words, NumPy is a fast and powerful library that helps Python work efficiently with numerical data and arrays.

## NumPy Arrays VS Python Lists.

- NumPy arrays and Python lists are used to store data, but they work differently.

- Python lists are flexible. We can add or remove items anytime, and we can store different types of data together like numbers, strings, and floats.

- NumPy arrays are more strict. After creating an array, its size is fixed. Also, NumPy arrays usually store only one type of data, like all integers or all floats.

- Because NumPy stores the same type of data together, it becomes much faster and uses less memory than Python lists.

- NumPy is specially made for mathematical and numerical calculations. It can handle large amounts of data very quickly and with less code.

- That is why NumPy is widely used in Data Science, Machine Learning, and scientific computing. Many libraries like Pandas and TensorFlow use NumPy internally.

- In simple words:

Python lists are flexible and easy to use.
NumPy arrays are faster and better for calculations.

## Creating NumPy Arrays.

In [2]:
#--> 1: np.array 

#1D (also know as a vector)
import numpy as np

a = np.array([1,2,3])
print(a)

print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D (also know as a metrix )

b = np.array([
    [1,2,3],[4,5,6]
    ])
    
print(b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [4]:
#3D (also know as a tensor)

c = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
    ])
    
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#--> 2: dtype (Create Array Of Your Choice)

x = np.array([1,2,3], dtype=float)
y = np.array([1,2,3], dtype=bool)
z = np.array([1,2,3], dtype=complex)

print(x)
print(y)
print(z)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [6]:
#--> 3: np.arange (use for create array)

p= np.arange(1,11)
q = np.arange(1,11,2)
r = np.arange(1,11, dtype=float)

print(p)
print(q)
print(r)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [7]:
#--> 4: reshape

aa = np.arange(1,11).reshape(5,2) #reshape(row, column) 
bb = np.arange(1,11).reshape(2,5) 

print(aa)
print("\n")
print(bb)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [8]:
#--> 5: np.ones and np.zeros and np.random

m = np.ones((3,4)) #pass tuple not array (row, column)
n = np.zeros((5,2)) 
o = np.random.random((3,2)) #give numben b/w 0 to 1

print(m)
print("\n")
print(n)
print("\n")
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


[[0.40634845 0.61461732]
 [0.27960913 0.13632659]
 [0.3657819  0.91671981]]


In [9]:
#--> 6: np.linspace (linear space)
#generate points at equal distance 

np.linspace(-10, 10, 10) #(lowerrange, upperrange, num of items)



array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [10]:
#--> 7: np.identity 

np.identity(3) #diagnoal items are 1 and others are 0 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Array Attributes

In [11]:
#--> 1: 
a1 = np.arange(10) #vector 
#by defult use int64
a11 = np.arange(10, dtype = np.int32) 

a2 = np.arange(12, dtype=float).reshape(3,4) #metrix
a3 = np.arange(8).reshape(2,2,2) #tensor

print(a1)
print('\n')
print(a2)
print('\n')
print(a3)

[0 1 2 3 4 5 6 7 8 9]


[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [12]:
#--> 2: ndim (Number of Dimensions)
print(a1.ndim )# says 1d array
print(a2.ndim) #says 2d array
print(a3.ndim) #says 3d array


1
2
3


In [13]:
#--> 3: shape
print(a1.shape )# how many items in dimensions (rows and column)
print(a2.shape) #(rows and column)
print(a3.shape) #(how many 2d array, rows, column  )

(10,)
(3, 4)
(2, 2, 2)


In [14]:
#--> 4: size
print(a1.size) # Number of items
print(a2.size)
print(a3.size)

10
12
8


In [15]:
#--> 5: itemsize (SIZE OF ITEM)

print(a1.itemsize) # Number of items
print(a11.itemsize)
print(a2.itemsize)
print(a3.itemsize)



8
4
8
8


In [16]:
#-->6: dtype

print(a1.dtype)
print(a11.dtype)
print(a2.dtype)
print(a3.dtype)

int64
int32
float64
int64


## Changing Datatype

very useful attribute


In [17]:
#--> 1: astype

#i only want to store age so why would i store in int64, i will store in int32

a3.astype(np.int32)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

## Array Operations

In [18]:
a10 = np.arange(12).reshape(3,4)
a20 = np.arange(12,24).reshape(3,4)

print(a10)
print(a20)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [19]:
#--> 1: Scalar operations

#arithmetic (-, +, * , /, % etc..)
a10 * 2   
#(matrix * scalar value)

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [20]:
#realtional (>, <, <=, >=, !=, etc..)
a20 > 15 


array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [21]:
#--> 2: vector operations

#arithmetic (-, +, * , /, % etc..)
a10 + a20 #if both array is same shape

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [22]:
#realtional (>, <, <=, >=, !=, etc..)
a10 < a20 

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Array Functions

don't need to remeber all, you can google it 


In [23]:
a12 = np.random.random((3,3))
a12 = np.round(a12*100)

print(a12)

[[35. 87. 28.]
 [94. 53. 38.]
 [15. 24. 62.]]


In [24]:
#--> 1: max/min/sum/prod(product)

np.max(a12)

#what if i want from only 1st row/column

np.max(a12,axis=1) # 0 - col , 1 - row

array([87., 94., 62.])

In [25]:
#--> 2: mean/median/std/var

# you can also use axis as well for row and column
np.mean(a12)

np.float64(48.44444444444444)

In [26]:
#--> 3: trigonomotric functions

np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [27]:
#--> 4: dot product (first column and second row match to hi possible hai)

a21 = np.arange(12).reshape(3,4)
a22 = np.arange(12, 24).reshape(4,3)

np.dot(a21,a22)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [28]:
#--> 5: log and exp (exponents)

np.exp(a12)

array([[1.58601345e+15, 6.07603023e+37, 1.44625706e+12],
       [6.66317622e+40, 1.04137594e+23, 3.18559318e+16],
       [3.26901737e+06, 2.64891221e+10, 8.43835667e+26]])

In [29]:
#--> 6: round/floor/ceil

np.floor(np.random.random((2,3))*100)


array([[ 6., 45., 51.],
       [ 0., 73., 34.]])

## Indexing and Slicing

In [70]:
a5 = np.arange(10)
a6 = np.arange(12).reshape(3,4)
a7 = np.arange(27).reshape(3,3,3)

print(a5)
print(a6)
print(a7)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [ ]:
#--> 1: Indexing 

# In 1D 
a5[-1]  # positiven, negative same as python

np.int64(9)

In [ ]:
# In 2D 

a6[1,2] #(row, column)

np.int64(6)

In [ ]:
# In 3D 

a7[1,0,1] #(which 2d array, row, column)


np.int64(5)

In [40]:
#--> 2: slicing 

# 1D

a5[2:10:2] #(same as python (start, end, skip))

array([2, 4, 6, 8])

In [ ]:
#2D 
 
# FORMAT: (row, column) #ask yourself whick row and which column 
# if you want continus row and column used single --> :
# if you want skip any row and column use double --> ::

a6[0,:] #(first row, {:} all column)

a6[:,2] # (all row, 2nd column)

a6[1:, 1:3] 

a6[::2,::3]

a6[::2, 1::2]

a6[1,0::3]

a6[0:2, 1::]

array([[1, 2, 3],
       [5, 6, 7]])

In [83]:

#3D 

#FORMAT --> (which 2D array, row, column)
# just give which 2D array and then same login for row and column as per 2D array
# at the end 3D array is made form 2D array so same logic 

a7[1] # for middle 2d array

a7[0::2] #i want first and last 2d array from 3d array

a7[0,1] #first 2d array 2nd row

a7[1,:,1] #2nd 2d array ka middle column

a7[2,1:,1:] # i want [22,23],[25,26]

a7[::2,0,0::2]

array([[ 0,  2],
       [18, 20]])

## Iterating 

(will use a5, a6 and a7 for this)


In [90]:
# 1D
for i in a5:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [91]:
#2D

for i in a6: #it will print one row in each iteration
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [92]:
#3D

for i in a7: #print one 2D array in each iteration
    print(i) 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [ ]:
# nditer (for print one element in each iteration)
 
for i in np.nditer(a7):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


## reshape, transpose, ravel

In [97]:
#--> 1: reshape

a31 = np.arange(27).reshape(3,3,3)

a31

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
#--> 2: traspose (row->column, column->row)

np.transpose(a31)

a31.T #easier syntax

array([[[ 0,  9, 18],
        [ 3, 12, 21],
        [ 6, 15, 24]],

       [[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]]])

In [ ]:
#--> 3: ravel (covert any dimensional array into 1d array)

np.ravel(a31) 
a31.ravel()   

#Both are same 
 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

## Stacking

[2 X 2] [2 X 2] these are the arrays

when we do staking:

horizontal : [2 X 4]
vertical : [4 X 2]

you can do with n number of arrays
no limitation

Rule: shape must be same of all arrays

In [111]:
a15 = np.arange(12).reshape(3,4)
a16 = np.arange(12,24).reshape(3,4)

print(a15)
print(a16)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [ ]:
#--> 1: horizontal stacking

np.hstack((a15,a16)) #np.hstack((1,2,3,...,n))



array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [116]:
#--> 2: vertical stacking

np.vstack((a15,a16))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

## Splitting 

#opposite of stacking

1. when you split : 

PART A  |  PART B 

this way it's not vertical split it's horizontal split 

2.when you split:

----

this way it's vertical split

In [118]:
a15

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#--> 1: horizontal splitting

np.hsplit(a15, 2) #(array,and num of equal split you want)


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [122]:
#--> 2: vertical splitting

np.vsplit(a15,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]