## np.sort

## numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)

return a sorted copy of an array

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [3]:
# code

import numpy as np

a = np.random.randint(1,100,15)

a

array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)

b

array([[49, 94, 47, 36],
       [21, 56, 51, 27],
       [33,  4,  7, 52],
       [85, 67, 76, 53],
       [91, 95, 95, 97],
       [26, 56, 32, 42]], dtype=int32)

In [ ]:
np.sort(a) 

array([ 3, 10, 16, 23, 34, 48, 51, 56, 61, 69, 73, 77, 78, 85, 94],
      dtype=int32)

In [ ]:
np.sort(b) #row wise

array([[36, 47, 49, 94],
       [21, 27, 51, 56],
       [ 4,  7, 33, 52],
       [53, 67, 76, 85],
       [91, 95, 95, 97],
       [26, 32, 42, 56]], dtype=int32)

In [ ]:
np.sort(b, axis=0) #column wise

array([[21,  4,  7, 27],
       [26, 56, 32, 36],
       [33, 56, 47, 42],
       [49, 67, 51, 52],
       [85, 94, 76, 53],
       [91, 95, 95, 97]], dtype=int32)

In [ ]:
np.sort(a) [::-1] # decreasing order

array([94, 85, 78, 77, 73, 69, 61, 56, 51, 48, 34, 23, 16, 10,  3],
      dtype=int32)

## np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [10]:
# code

np.append(a, 200)

array([ 48,  94,  56,  77,  23,  34,  61,  51,  78,  69,  10,   3,  16,
        85,  73, 200])

In [11]:
b

array([[49, 94, 47, 36],
       [21, 56, 51, 27],
       [33,  4,  7, 52],
       [85, 67, 76, 53],
       [91, 95, 95, 97],
       [26, 56, 32, 42]], dtype=int32)

In [13]:
np.append(b, np.ones((b.shape[0],1)),axis = 1) # all 1 in new last column

array([[49., 94., 47., 36.,  1.],
       [21., 56., 51., 27.,  1.],
       [33.,  4.,  7., 52.,  1.],
       [85., 67., 76., 53.,  1.],
       [91., 95., 95., 97.,  1.],
       [26., 56., 32., 42.,  1.]])

## np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [14]:
# code

c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [15]:
np.concatenate((c,d),axis = 0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
np.concatenate((c,d),axis = 1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

## np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [18]:
# code

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [19]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

## np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [22]:
# code

a # 1d array
print(a.shape)

(15,)


In [25]:
print(np.expand_dims(a, axis = 0))

print(np.expand_dims(a, axis = 1))


[[48 94 56 77 23 34 61 51 78 69 10  3 16 85 73]]
[[48]
 [94]
 [56]
 [77]
 [23]
 [34]
 [61]
 [51]
 [78]
 [69]
 [10]
 [ 3]
 [16]
 [85]
 [73]]


## np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [26]:
a

array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [28]:
# find all indices with value grater than 50

np.where(a > 50) # return index position

(array([ 1,  2,  3,  6,  7,  8,  9, 13, 14]),)

In [ ]:
# replace all value > 50 with 0

#np.where(condition,true,false)
np.where(a>50,0,a) #true hai to replace false has hai to same as it is.

array([48,  0,  0,  0, 23, 34,  0,  0,  0,  0, 10,  3, 16,  0,  0],
      dtype=int32)

In [30]:
np.where(a%2==0, 0, a)

array([ 0,  0,  0, 77, 23,  0, 61, 51,  0, 69,  0,  3,  0, 85, 73],
      dtype=int32)

## np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

argmax brother argmin for minimum value index


In [32]:
 # code

x = np.random.randint(1,100,10)
print(x)

print(np.argmax(x))


[13 77 37 69  6 86  6 11 65 13]
5


In [33]:
b

array([[49, 94, 47, 36],
       [21, 56, 51, 27],
       [33,  4,  7, 52],
       [85, 67, 76, 53],
       [91, 95, 95, 97],
       [26, 56, 32, 42]], dtype=int32)

In [35]:
np.argmax(b,axis=1) # for row


array([1, 1, 3, 0, 3, 1])

In [ ]:
np.argmax(b, axis=0) # for column

array([4, 4, 4, 4])

In [38]:
np.argmin(b,axis=1)

array([3, 0, 1, 3, 0, 0])

## np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [39]:
a

array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [40]:
np.cumsum(a)

array([ 48, 142, 198, 275, 298, 332, 393, 444, 522, 591, 601, 604, 620,
       705, 778])

In [42]:
print(b)

print(np.cumsum(b,axis = 0))


[[49 94 47 36]
 [21 56 51 27]
 [33  4  7 52]
 [85 67 76 53]
 [91 95 95 97]
 [26 56 32 42]]
[[ 49  94  47  36]
 [ 70 150  98  63]
 [103 154 105 115]
 [188 221 181 168]
 [279 316 276 265]
 [305 372 308 307]]


In [43]:
print(b)

print(np.cumsum(b,axis = 1))


[[49 94 47 36]
 [21 56 51 27]
 [33  4  7 52]
 [85 67 76 53]
 [91 95 95 97]
 [26 56 32 42]]
[[ 49 143 190 226]
 [ 21  77 128 155]
 [ 33  37  44  96]
 [ 85 152 228 281]
 [ 91 186 281 378]
 [ 26  82 114 156]]


In [44]:
# np.cumprod

a

array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [45]:
np.cumprod(a)

array([                  48,                 4512,               252672,
                   19455744,            447482112,          15214391808,
               928077900288,       47331972914688,     3691893887345664,
         254740678226850816,  2547406782268508160,  7642220346805524480,
       -6851682967078469632,  7902758157035732992,  5052279178612408320])

## np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [49]:
# code

a


array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [50]:
np.percentile(a,100)

np.float64(94.0)

## np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [ ]:
# code

np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([1, 2, 1, 1, 1, 2, 2, 3, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

## np.corrcoef
Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [54]:
#code

salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

## np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [55]:
# code
a

array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [57]:
items = [10,20,30,40,50,60,70,80,90,100]

print(np.isin(a, items))

print(a[np.isin(a, items)])

[False False False False False False False False False False  True False
 False False False]
[10]


## np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [58]:
# code

a 

array([48, 94, 56, 77, 23, 34, 61, 51, 78, 69, 10,  3, 16, 85, 73],
      dtype=int32)

In [59]:
np.flip(a)

array([73, 85, 16,  3, 10, 69, 78, 51, 61, 34, 23, 77, 56, 94, 48],
      dtype=int32)

In [60]:
b

array([[49, 94, 47, 36],
       [21, 56, 51, 27],
       [33,  4,  7, 52],
       [85, 67, 76, 53],
       [91, 95, 95, 97],
       [26, 56, 32, 42]], dtype=int32)

In [ ]:
np.flip(b) # row + column flip 

array([[42, 32, 56, 26],
       [97, 95, 95, 91],
       [53, 76, 67, 85],
       [52,  7,  4, 33],
       [27, 51, 56, 21],
       [36, 47, 94, 49]], dtype=int32)

In [ ]:
np.flip(b,axis=0) #for column

array([[26, 56, 32, 42],
       [91, 95, 95, 97],
       [85, 67, 76, 53],
       [33,  4,  7, 52],
       [21, 56, 51, 27],
       [49, 94, 47, 36]], dtype=int32)

In [63]:
np.flip(b, axis=1) # for row

array([[36, 47, 94, 49],
       [27, 51, 56, 21],
       [52,  7,  4, 33],
       [53, 76, 67, 85],
       [97, 95, 95, 91],
       [42, 32, 56, 26]], dtype=int32)

## np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [66]:
# code

a 

array([110,   5,  56,  77,  23,  34,  61,  51,  78,  69,  10,   3,  16,
        85,  73], dtype=int32)

In [68]:
np.put(a, [0,1],[111, 222]) # perment changes

In [69]:
a

array([111, 222,  56,  77,  23,  34,  61,  51,  78,  69,  10,   3,  16,
        85,  73], dtype=int32)

## np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [71]:
a

array([111, 222,  56,  77,  23,  34,  61,  51,  78,  69,  10,   3,  16,
        85,  73], dtype=int32)

In [75]:
np.delete(a, 0)

array([222,  56,  77,  23,  34,  61,  51,  78,  69,  10,   3,  16,  85,
        73], dtype=int32)

In [76]:
np.delete(a, [1,2,3])

array([111,  23,  34,  61,  51,  78,  69,  10,   3,  16,  85,  73],
      dtype=int32)

## Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

NumPy set functions are useful for finding unique/common/different values between arrays quickly and easily.

In [77]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [78]:
np.intersect1d(m, n)

array([3, 4, 5])

In [79]:
np.setdiff1d(m,n)

array([1, 2])

In [83]:
np.setxor1d(m,n) # remove common

array([1, 2, 6, 7])

In [86]:
np.in1d(m,n)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_9188\207282267.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False,  True,  True,  True])

## np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [87]:
# code

a

array([111, 222,  56,  77,  23,  34,  61,  51,  78,  69,  10,   3,  16,
        85,  73], dtype=int32)

In [88]:
np.clip(a, a_min=25, a_max=75)

array([75, 75, 56, 75, 25, 34, 61, 51, 75, 69, 25, 25, 25, 75, 73],
      dtype=int32)

## np.swapaxes

Used to swap two axes (dimensions) of an array.

In [93]:
a = np.array([[[1,2],[3,4],[5,6],[7,8]]])

print(a.shape)
print(a)

(1, 4, 2)
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [94]:
np.swapaxes(a,0,1)

array([[[1, 2]],

       [[3, 4]],

       [[5, 6]],

       [[7, 8]]])

## np.uniform

Generated random decimal numbers between a range.

In [95]:
#np.random.uniform(start, end, size)

np.random.uniform(1,10,5)

array([4.57326423, 3.53054754, 7.64529265, 9.79693553, 3.67622237])

## np.count_nonzero

Counts nubers that are NOT zero.

In [96]:
a = np.array([1,0,2,0,5])

np.count_nonzero(a)

np.int64(3)

## np.tile

Repeats an array multiple times.

In [97]:
a = np.array([1,2,3])

np.tile(a,2)

array([1, 2, 3, 1, 2, 3])

In [98]:
a = np.array([1,2,3])

np.tile(a,4)

array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [ ]:
np.tile(a,(2,2)) # in 2d format

array([[1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3]])

## np.repeat()

Repeats each element.

In [100]:
a = np.array([1,2,3])

np.repeat(a,2)

array([1, 1, 2, 2, 3, 3])

## np.allclose

Checks if arrays are almost equal.

Useful for decimal/floating point comparisons.

In [ ]:

a = np.array([1.00001,2.00001])
b = np.array([1.00002,2.00002])

print(np.allclose(a,b))

True


## np.equal

Checks exact equality element by element.

In [104]:
a = np.array([1,2,3])
b = np.array([1,5,3])

np.equal(a,b)

array([ True, False,  True])